[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
engine = { path = "../engine" }

[[bin]]
name = "empyre"
path = "src/main.rs"
